### ISSUE TITLE
failed on cuInit: CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by traderpedroso** [heterodb/pg-strom#574]
when try to find the devices using 

```
postgres=# SELECT * FROM pgstrom.device_info;
 device_nr | aindex | attribute | value 
-----------+--------+-----------+-------
(0 rows)
```

my setup is rocky linux 8  running on lxc proxmox container gpu passthrough so cuda are working ok on tensorflow and pytorch using the same setup 

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
| 41%   45C    P0    15W / 125W |      0MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```
```
out 26 20:00:46 portainer systemd[1]: postgresql-13.service: Succeeded.
out 26 20:00:46 portainer systemd[1]: Stopped PostgreSQL 13 database server.
out 26 20:00:46 portainer systemd[1]: Starting PostgreSQL 13 database server...
out 26 20:00:46 portainer postmaster[44813]: 2022-10-26 20:00:46.244 UTC [44813] LOG:  NVRTC 11.8 is successfully loaded.
out 26 20:00:46 portainer postmaster[44813]: 2022-10-26 20:00:46.247 UTC [44813] LOG:  HeteroDB Extra module loaded [api_version=20211018,cufile=off,nvme_strom=off]
out 26 20:00:46 portainer postmaster[44813]: 2022-10-26 20:00:46.247 UTC [44813] LOG:  PG-Strom version 3.3 built for PostgreSQL 13 (git: v3.3-2)
out 26 20:00:46 portainer postmaster[44814]: gpuinfo:459  failed on cuInit: CUDA_ERROR_UNKNOWN
out 26 20:00:47 portainer postmaster[44813]: 2022-10-26 20:00:47.118 UTC [44813] LOG:  redirecting log output to logging collector process
out 26 20:00:47 portainer postmaster[44813]: 2022-10-26 20:00:47.118 UTC [44813] HINT:  Future log output will appear in directory "log".
```

```
/usr/pgsql-13/bin/gpuinfo
gpuinfo:459  failed on cuInit: CUDA_ERROR_UNKNOWN
```

**Comment by traderpedroso** [comment]
i found the solution for that
 creating /etc/udev/rules.d/70-nvidia.rules
and reboot is now working i follow the tutorial from this url [gpu-passthrough](https://theorangeone.net/posts/lxc-nvidia-gpu-passthrough/)
```
KERNEL=="nvidia", RUN+="/bin/bash -c '/usr/bin/nvidia-smi -L && /bin/chmod 666 /dev/nvidia*'"
KERNEL=="nvidia_uvm", RUN+="/bin/bash -c '/usr/bin/nvidia-modprobe -c0 -u && /bin/chmod 0666 /dev/nvidia-uvm*'"
```

**Comment by kaigai** [comment]
We don't care about issues prior to v3.x or before.
Needs to confirm whether it is reproducible on the v5.x series or not.
